### ISSUE TITLE
Which tool are you using to convert .wz to .nx?

### ISSUE THREAD

**Issue by devdilson** [Kaioru/Edelstein#1]

**Comment by Kaioru** [comment]
Hello, thanks for checking out Edelstein!

To convert WZ files to NX I used NoLifeWzToNx which you can find around the internet somewhere or you can also use [wz2nx](https://github.com/angelsl/wz2nx) by angelsl to convert the files.

Another issue you might face is that the server will try to read a NX file, Server.nx. To get that file, check out [Server.NX](https://github.com/kaioru/server.nx)

Feel free to ask if you have any more questions! 🤤

**Comment by devdilson** [comment]
Thanks :)
