### ISSUE TITLE
Exception on entering Lith Harbour general store

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#13]
![image](https://user-images.githubusercontent.com/2548763/58768526-cbacc280-859c-11e9-844e-fcfb7f372821.png)

**Comment by Kaioru** [comment]
Could I have the Field ID for the map?

**Comment by Bia10** [comment]
hmmm i guess 4000005 (not checked)

**Comment by Bia10** [comment]
correction 
104000000 // Lith Harbor : Lith Harbor
104000001 // Lith Harbor : Lith Harbor Armor Store
104000002 // Lith Harbor : Lith Harbor General Store
104000003 // Lith Harbor : Lith Harbor Weapon Store
