### ISSUE TITLE
Few bugs i noticed

### ISSUE THREAD

**Issue by R3DIANCE** [Kaioru/Edelstein#16]
![image](https://user-images.githubusercontent.com/13523121/58904529-611c9380-8710-11e9-82b9-66d961d0e973.png)

After loging in with new account and re-loging the account username is scrambled with random characters / duplicates.
- Any localhost with source?
- MySQL will be great!
- Exp not working?

**Comment by Bia10** [comment]
Yes there is localhost currently we share it on discord only.

MySQL would be great indeed, however as far as i was informed there is no compatibility with features being used by Edelstein storage system and MySQL yet. So PostgreSQL, InMemory are currently the options.

Exp are working as in increasing... level up is sort of working only by command for now, chat effect of exp increase is going to follow soon.

**Comment by R3DIANCE** [comment]
@Bia10 thanks! what about the LiteDB thingy?
and where i can get the discord?

**Comment by Kaioru** [comment]
@R3DIANCE Hello, thanks for checking Edelstein out!

1. LiteDB is a local storage system that'll store your data locally into a file, which is also the default configuration of the container service. It takes 0 additional setup and would be ideal for testing and development.
2. The username/password issue will be resolved when using the proper localhost.
3. Mob EXP is not implemented as of now.
