### ISSUE TITLE
Standing on air?

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#17]
It seems something is missing from scene or is this intended?

![air](https://user-images.githubusercontent.com/2548763/58906260-d2a61300-870b-11e9-8fed-50ee442423be.png)

**Comment by Bia10** [comment]
okay its Duey Package Deliverer's truck what i am standing on, however it might be client/WZ specific bug.

**Comment by Maxcloud** [comment]
It's a platform bug that was fixed in later revisions of 95.
