### ISSUE TITLE
!set job command accepts nearly any integer input

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#19]
the allowed input should be limited to available jobs only red from either constants or the game files itself

so !set job 98641657 does executes which ofcs leads to unexpected behavior

![ggjob](https://user-images.githubusercontent.com/2548763/58917834-32121c00-8728-11e9-9cb3-7cb60660c73f.png)

**Comment by R3DIANCE** [comment]
its working perfect tho, you need use correct ids.
i shared those in temporary discord.

**Comment by Bia10** [comment]
Outdated issue, current is already mentioned in #82
