### ISSUE TITLE
crash on script

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#23]
the script is in the scripts PR

![crash](https://user-images.githubusercontent.com/2548763/58922107-d781bb80-8739-11e9-95b0-ea74b02b8595.png)

**Comment by Kaioru** [comment]
This happens when a menu is added into a .say dialog like so:

```lua
self.say("Have you got something to say?\r\n#b#L0# I would like to learn more about pirates..#l")
```

Change it to:
```lua
self.ask_menu("Have you got something to say?", {
    [0] = "I would like to learn more about pirates.."
})
```
