### ISSUE TITLE
Missing script functionality

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#24]
currently these are missing functions for scipts:
disableUI() - hides UI
lockUI() - prevent players actions
directionmode()
setStandAloneMode()
PortalSE()
IncreaseSlotLimit()

**Comment by Kaioru** [comment]
https://github.com/Kaioru/Edelstein/commit/d4af001a750a1a569e593b5cdef3345cb333e720 - Adds `GetInventoryLimit` and `SetInventoryLimit` for example:
```lua
inventory = target.get_inventory()

-- 0x1 - Equip, 0x2 - Consume, 0x3 - Install, 0x4 - Etc, 0x5 - Cash
inventory.get_inventory_limit(0x1)
inventory.set_inventory_limit(0x1, 48)
```
https://github.com/Kaioru/Edelstein/commit/bbfe1e4458da14c67a7bb1878444eccb4ba760df - Adds settings of DirectionMode and StandAloneMode like so: 
```lua
target.direction_mode = true -- or false
target.stand_alone_mode = true -- or false
```
https://github.com/Kaioru/Edelstein/commit/a5708440fc29491fe4a9d32a335d629f3c766147 - Adds `PlayPortalSoundEffect` used like so:
```lua
target.play_portal_sound_effect()
```

**Comment by Bia10** [comment]
great now we need just 

```java
c.getSession().write(UIPacket.IntroDisableUI(false));
c.getSession().write(UIPacket.IntroLock(false));

    public static byte[] IntroLock(boolean enable) {
        MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();

        mplew.writeShort(SendPacketOpcode.CYGNUS_INTRO_LOCK.getValue());
        mplew.write(enable ? 1 : 0);
        mplew.writeInt(0);

        return mplew.getPacket();
    }

    public static byte[] IntroDisableUI(boolean enable) {
        MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();

        mplew.writeShort(SendPacketOpcode.CYGNUS_INTRO_DISABLE_UI.getValue());
        mplew.write(enable ? 1 : 0);

        return mplew.getPacket();
    }
```

v90?

**Comment by Kaioru** [comment]
From what I see, LockUI is not available in v95
![image](https://user-images.githubusercontent.com/6829787/58926848-2140c500-877f-11e9-831a-796cc0b0f99f.png)
The opcode for LockUI in other versions usually lie between OpenUIWithOption and SetDirectionMode

**Comment by Bia10** [comment]
okay but there has to be a way to close UI in video scenes?

**Comment by Kaioru** [comment]
`target.direction_mode = true` removes and disables UI from my tests.
`target.direction_mode = false` re-enables UI controls.

I'm not sure what StandAloneMode does though. Might actually be `IntroDisableUI` in your reference
