### ISSUE TITLE
Cant add sp to skill

### ISSUE THREAD

**Issue by R3DIANCE** [Kaioru/Edelstein#25]
![image](https://user-images.githubusercontent.com/13523121/58961155-3e8e8700-87b1-11e9-904c-e029d9b474c4.png)

![image](https://user-images.githubusercontent.com/13523121/58961028-09823480-87b1-11e9-93d5-382435d3d90b.png)

**Comment by Bia10** [comment]
Well this is actually means something else:
Your missing SP obtained from lvl 30-70 to use.
You have already used your 30-51 SP points.

dunno wherever this is client sided or just server bug, from position of being very gmslike theres not much wrong going on.

**Comment by R3DIANCE** [comment]
i found what was the issue, its because of the level (51) didn't match the skills 2nd class job, should be level (60).
