### ISSUE TITLE
!set sp command doesn't give sp

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#26]
rather it displays a weird msg

![sp](https://user-images.githubusercontent.com/2548763/58972182-418f7480-87bd-11e9-915d-f118b2f47c17.png)

**Comment by R3DIANCE** [comment]
for explorers do !set sp 30
for non explorers or other based use !set sp 30 -e `<jobclasslevel>` //jobclasslevel is a fist second third forth tabs, like for first job tab you do 1 for second you do 2 etc..
