### ISSUE TITLE
Special Training Invitation is not given by Ferdi

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#27]
Ferdi, the Edelstein School Headmaster doesn't give 2031010 upon completing the LVL 10  resistance quest. If manually given then work as intended.

**Comment by R3DIANCE** [comment]
You need make `q<questid>s.lua` example script:
```
inventory = target.get_inventory()
speaker = self.as_speaker(2007)
quest = target.get_quest(<questid>)
inventory.add(2031010, 1)
quest.accept()
quest.complete()
```

**Comment by Kaioru** [comment]
Quest checks and actions are not implemented fully yet, only the rough quest framework.
So once those are in, all quests will give the correct items based on the loaded data.

**Comment by Kaioru** [comment]
Fixed as of https://github.com/Kaioru/Edelstein/commit/4a0a9f3f6882a67a070fe60099b37aa94e4a8f96
