### ISSUE TITLE
Mob movement generates exceptions

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#28]
Map: 102010000 // South Rocky Mountain : Perion Southern Ridge
Mobs:  100005 // Stump, 3230300 // Jr. Boogie, 3230301 // Jr. Boogie

exceptions being thrown:

![mobs dont spawn](https://user-images.githubusercontent.com/2548763/59029216-f9745e80-885d-11e9-9552-765cc53f4001.png)

**Comment by Bia10** [comment]
heres same event from viewpoint of release mode

![rope](https://user-images.githubusercontent.com/2548763/59120356-7cc4ab80-8955-11e9-9c58-30222bd00f06.png)

**Comment by Kaioru** [comment]
This issue stemmed from packet decoding relying on exceptions to retry,
Shouldn't happen anymore as length of input is being checked before accessing during the decoding process.
