### ISSUE TITLE
Crash when entering cash shop

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#30]
![crashcsh](https://user-images.githubusercontent.com/2548763/59109580-935f0880-893d-11e9-972a-c9e9d6e66ab5.png)

**Comment by Kaioru** [comment]
I would need some details to test this out:
1. Which services are you running (container, etc)
2. What configurations are you using for the Database and Distributed Models

**Comment by Bia10** [comment]
Everything is default as is shipped.

**Comment by Bia10** [comment]
rls mode 

![rlsmode](https://user-images.githubusercontent.com/2548763/59121196-ba2a3880-8957-11e9-8b74-7ee1ef1da662.png)
