### ISSUE TITLE
List of non-working skills

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#38]
[fpWizards] : (mpEater) - doesn't work
[fpWizards] : (slow) - does't apply mob status change
[fpWizards]  : (poisonBreath) - does't apply mob status change
[fpMage]  : (poisonMist) - doesn't spawn mist entity
[fpMage]  : (teleportMastery) - doesn't apply buff
[ilWizards]  : (mpEater) - doesn't work
[ilMage]  : (teleportMastery) - doesn't apply buff
[cleric] : (mpEater)  - doesn't work
[cleric] : (heal) - doesn't heal
[priest] : (holySymbol) - doesn't increase exp gain
[priest] : (door)  - doesn't spawn door entity
[priest] : (doom) - doesn't apply status change
[hunter] : (arrowBomb) - does't apply mob status change, if dmg kills mob, death anim. gets messed
[hunter] : (powerKnock-Back) - does't apply mob status change, if dmg kills mob, death anim. gets messed
[ranger] : (puppet) - entity is not summoned
[ranger] : (silverHawk) - entity is not summoned
[ranger] : (inferno) - skill cannot be leveled up
[rogue] : (disorder) - doesn't apply mob effect
[assasin] : (drain) - doesn't heal caster
[hermit] : (alchemist) - bonus is not applied 
[hermit] : (mesoUp) -  bonus is not applied
[hermit] : (shadowWeb) - doesn't work 
[hermit] : (darkFlare) - doesn't work 
[hermit] : (shadowMeso) - does't consume meso, bonus dmg not applied 
[bandit] : (steal) - doesn't steal items
[chiefBandit] : (pickpocket) -  bonus is not applied
[chiefBandit] : (mesoExplosion) - works very weirdly first no dmg applied then insta kill
[chiefBandit] : (darkFlare)  - doesn't work 
[chiefBandit] : (charka) - health/mana doesn't change
[chiefBandit] : (mesoGuard)  - doesn't work
[pirate] : (dash) - doesn't apply its buff
[outlaw] : (rollOfTheDice) - doesn't apply buff
[marauder] : (rollOfTheDice) - doesn't apply buff
[marauder] : (energyCharge) - doesn't work

the list continues on, however generally speaking:
case 1: mob status not applied
case 2: skill doesn't heal user/allies
case 3: no summoned entity
case 4: no transformation skill applied
case 5: no buff or bonus applied

**Comment by Kaioru** [comment]
If I'm not wrong, not all skills buffs are handled yet.
I'll use this issue to track the skills not done yet.
