### ISSUE TITLE
Are you using a localhost for testing?

### ISSUE THREAD

**Issue by devdilson** [Kaioru/Edelstein#4]
I released a localhost sometime ago in ragezone, but it has a bug with the user login / password. 

So I would like to suggest one of the following options: 

- Fix the current localhost. 
- Create a 'localhost' dll where client fixes could be applied(windows 10 fix, make client load faster, encode byte specifying if damage was critical or not, etc.).

In my view, having a DLL that can be used to extend the client would be killer. 

Best,

**Comment by Kaioru** [comment]
Hello again!

Having a DLL would be the end goal here as we wouldn't need to distribute a localhost.. However, I'm not as experienced in creating hooks and client hacks so this wouldn't be a priority for now.

Feel free to start a repo and project for it to get the ball rolling though!
