### ISSUE TITLE
Double look-up in dictionaries

### ISSUE THREAD

**Issue by gilmatok** [Kaioru/Edelstein#52]
```
 public ITemplate Get(int id)
        {
            return !Templates.ContainsKey(id) ? null : Templates[id];
        }
```
This is a double look-up. Use "Dicitonary.TryGetValue" instead.

**Comment by Kaioru** [comment]
Noted, I'll look around the source code for similar issues too.
Thanks so much for letting me know!

**Comment by Kaioru** [comment]
After 2 years and a few more reiterations, this should now be resolved.

**Comment by gilmatok** [comment]
@Kaioru happt to see you're still maintaining this. Good work!
