### ISSUE TITLE
What client files to connect?

### ISSUE THREAD

**Issue by JeffBusch** [Kaioru/Edelstein#55]
Hello,

I got this compiled and running on my Raspberry Pi 4 and realized all the links for a v95 localhost are dead...

Just wondering if someone could point me in the right direction on connecting to this. I'm super out of the loop on MS private server stuff, just trying to test this out for fun.

Thanks!

**Comment by Kaioru** [comment]
Hey! Drop me a DM on Discord: Kaioru#1256
