### ISSUE TITLE
Some setup issues

### ISSUE THREAD

**Issue by BuilderExSA** [Kaioru/Edelstein#59]
1. WorldTemplateRepository.cs (Edelstein-dev\src\common\Edelstein.Common.Gameplay.Stages.Login\Templates) has Continent.img mistakenly named as World.img in line 23

Nuget also needs to be called manually to restore LiteDB but that's not really an issue, just for documentation purposes

**Comment by Kaioru** [comment]
Hey! World.img is actually right, but I've not updated the Server.NX downloads to include World.img.
World.img currently just contains the names of all the worlds. See: https://github.com/Kaioru/Server.NX/blob/master/src/World.img.json
