### ISSUE TITLE
Better handling of ungraceful termination.

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#74]
There are many possibilities why Stop method wont run this open possibility of stage registration continually failing due to stages already being registered on a "dead instance".

So either cover possibilities of ungraceful termination 

or 

Ensure there are no leftovers from previous instance.

**Comment by Kaioru** [comment]
7e44b191d95d5f3b90c84ebbf9ea754c2e1e44c5 and 8802ccdd09d5962fe6e01c699a0864f692d8eebf fixes the issue of server registry not being able to self restore properly when records not deregistered properly.

 Also adds preprocessor to not run graceful shutdown with quiet period during debug builds.
