### ISSUE TITLE
[Feature] Allow different ordering for deserialization of UserOnPacketCheckPassword

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#75]
![image](https://github.com/Kaioru/Edelstein/assets/2548763/ef1e89ce-3b9b-4a62-a3ae-be1be6c19fb6)

Edit: Apparently there are 2 types of ordering for username/password. Add functionality to configure for each type.

**Comment by Kaioru** [comment]
Adding this to protocol and common for now,
This together with autoregister will be in Rue in the future when plugin configs are done
