### ISSUE TITLE
[Bug] Failure to convert NxNode from int64 to string.

### ISSUE THREAD

**Issue by Bia10** [Kaioru/Edelstein#77]
![image](https://github.com/Kaioru/Edelstein/assets/2548763/658f39ec-383a-4325-b543-8c17bbfa14a8)

Possible adjustments:

- Add try/catch/finaly.
- Log the issue for later inspection.
- Return null/default.

**Comment by Kaioru** [comment]
As of the update to Duey 2.0, this should not be an issue anymore.
There are no more internal casting made in Duey, all values are resolved as-is.
